version: '3.1'

services:
  web:
    build:
        context: .
        dockerfile: Dockerfile    # env_file:
    #   - .env
    ports:
      - "3030:3030"
    volumes:
      - ./:/app
    command:
      - /bin/bash
      - -c
      - |
        rails s -b 0.0.0.0 -p 3030
